// Theme configuration
export const theme = {
  colors: {
    primary: '#55B685',
    secondary: '#6B98D4',
    background: '#F8F9FA',
    card: '#FFFFFF',
    text: '#1A1A1A',
    textSecondary: '#6E6E6E',
    border: '#E0E0E0',
    notification: '#FF3B30',
    success: '#34C759',
    error: '#FF3B30',
    warning: '#FF9500',
    inactive: '#BDBDBD',
  },
  dark: {
    primary: '#55B685',
    secondary: '#4A6FA5',
    background: '#121212',
    card: '#1E1E1E',
    text: '#F8F9FA',
    textSecondary: '#A0A0A0',
    border: '#2C2C2C',
    notification: '#FF453A',
    success: '#30D158',
    error: '#FF453A',
    warning: '#FF9F0A',
    inactive: '#555555',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 24,
    round: 9999,
  },
  typography: {
    fontSizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
    },
    fontWeights: {
      light: '300',
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
  },
};